### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by spongxin** [Hyrmm/chaoxingSpider#4]
浏览登录页发现需要输入验证码，对应post中`numcode`字段

**Comment by Hyrmm** [comment]
这个登录接口是不需要验证码的

**Comment by Hyrmm** [comment]
> 

看了下，不是验证码的问题，登录表单提交的密码 加密方式变了，不是md5加密，正在解决！

**Comment by spongxin** [comment]
感谢大佬已经能刷课了！ 
另外问一下当前可以修改倍速吗

**Comment by Hyrmm** [comment]
> 感谢大佬已经能刷课了！ 另外问一下当前可以修改倍速吗

已经跟新!
